language: cpp

compiler: clang

before_script:

- sudo apt-get install libboost-test-dev -y

- sudo apt-get install doxygen -y

script:

- cmake .

- cmake --build .

- cmake --build . --target test

- cmake --build . --target package

deploy:

  provider: script

  skip_cleanup: true

  script:

  - curl -T print_ip-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uvabon:$BINTRAY_API_KEY "https://api.bintray.com/content/vabon/repo01/print_ip/$TRAVIS_BUILD_NUMBER/print_ip-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
